os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc


install:
  - pip install cython;
  - pip install cpp-coveralls
  - pip install coverage
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $TRAVIS_BUILD_DIR/tests && make;

script:
  # Run tests
  - cd $TRAVIS_BUILD_DIR/tests && coverage run runScript.py;
  - coverage report;

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
