os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc


install:
  - pip install cython;
  - pip install cpp-coveralls;

script:
  # Run tests
  # We thrown away the existing repo in Docker, and copy the new one in-place
  #- cd $TRAVIS_BUILD_DIR/tests && make;
  #- cd $TRAVIS_BUILD_DIR/tests && python runScript.py;
  - cd $TRAVIS_BUILD_DIR && ./runTest.sh;
  
after_success:
  - coveralls;
