os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc

env:
  global:
    - COVERALLS_PARALLEL=true
  jobs:
    - pip install --user cpp-coveralls
    - pip install --user coveralls

notifications:
  webhooks: https://coveralls.io/webhook
  
install:
  - pip install cython
  
script:
  # Run tests
  # We thrown away the existing repo in Docker, and copy the new one in-place
  #- cd $TRAVIS_BUILD_DIR/tests && make && cd $TRAVIS_BUILD_DIR/tests && python runScript.py && mv *.C *.H *.cpp build/temp*/ && coveralls --exclude build/temp*/*.cpp; 
  - cd $TRAVIS_BUILD_DIR/tests && make
  - coverage run --source=runTest runScript.py
  - mv *.C *.H *.cpp build/temp*/
  - coveralls --exclude build/temp*/*.cpp
  #- cd $TRAVIS_BUILD_DIR/tests && python runScript.py && mv *.C *.H *.cpp build/temp*/;
  # - coveralls --exclude build/temp*/*.cpp
  #- cd $TRAVIS_BUILD_DIR && chmod 755 runTest.sh && ./runTest.sh;
