os: linux
dist: bionic
language: generic

services:
    - docker

env:
  global:
    - PWD = $(pwd)
  jobs:
    - DOCKER_TAG=latest


install:
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $(PWD)/tests && make

script:
  # Run tests
  - cd $(PWD)/tests && python runScript.py
