os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc


install:
  - pip install cython;
  - pip install coveralls;

script:
  # Run tests
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $TRAVIS_BUILD_DIR/tests && make;
  - cd $TRAVIS_BUILD_DIR/tests && coverage run --source=runTest runScript.py;
  - coveralls
  #- cd $TRAVIS_BUILD_DIR/tests && python runScript.py && mv *.C *.H *.cpp build/temp*/;
  # - coveralls --exclude build/temp*/*.cpp
  #- cd $TRAVIS_BUILD_DIR && chmod 755 runTest.sh && ./runTest.sh;
