os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc


install:
  - pip install cython;
  - pip install cpp-coveralls;

script:
  # Run tests
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $TRAVIS_BUILD_DIR/tests && make;
  - cd $TRAVIS_BUILD_DIR/tests && python runScript.py && cp *.C *.H *.cpp build/temp.linux-x86_64-2.7/;
  - coveralls --exclude *.cpp
  #- cd $TRAVIS_BUILD_DIR && chmod 755 runTest.sh && ./runTest.sh;
