os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

gcc:
  - "7.5"


env:
  global:
    - PWD = $(pwd)
  jobs:
    - DOCKER_TAG=latest


install:
  - cd $PWD && pip install cython
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $PWD/tests && make

script:
  # Run tests
  - cd $PWD/tests && python runScript.py
