os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc


env:
  global:
    - TESTDIR = $(pwd)
  jobs:
    - DOCKER_TAG=latest


install:
  - cd $TESTDIR && pip install cython
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $TESTDIR/tests && make

script:
  # Run tests
  - cd $TESTDIR/tests && python runScript.py
