os: linux
dist: bionic
language: generic
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc


install:
  - pip install cython;
  - pip install coverage;
  - pip install coveralls;
  - pip install testflo==1.3.6;
  # We thrown away the existing repo in Docker, and copy the new one in-place
  - cd $TRAVIS_BUILD_DIR/tests && make;

script:
  # Run tests
  - cd $TRAVIS_BUILD_DIR/tests && python runScript.py;

after_success:
- coveralls;
